
services:
  redis:
    image: "redis:alpine"
  rabbit:
    container_name: "rabbitmq_container"
    ports:
      - 5672:5672
      - 15672:15672
    hostname: rabbit
    
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  app:
    container_name: "flask_container"
    image: flask-teste
    command: flask run --port 5000 --host 0.0.0.0
    ports:
      - 5000:5000
    restart: on-failure
    depends_on:
      - rabbit
    volumes:
      - .:/app
